//208005587 Itay Sharfer
import java.util.Map;
/**
 * The And class contains attributes and different methods used on and expressions.
 */
public class And extends BinaryExpression implements Expression {
    /**
     * The And method constructs a new And instance.
     * @param left - the left expression in the instance.
     * @param right - the right expression in the instance.
     */
    public And(Expression left, Expression right) {
        super(left, right);
    }


    /**
     * The evaluate method calculates the truth value of the instance based on a mapping of variables and values.
     * @param assignment - a map instance of variables and values
     * @return - The truth value of the instance based on the mapping.
     * @throws Exception
     */
    public Boolean evaluate(Map<String, Boolean> assignment) throws Exception {
        return (this.left.evaluate(assignment) && this.right.evaluate(assignment));
    }

    /**
     * The evaluate method calculates the truth value of the instance.
     * @return - The truth value of the instance.
     * @throws Exception
     */
    public Boolean evaluate() throws Exception {
        return (this.left.evaluate() && right.evaluate());
    }


    /**
     * The toString method converts the instance to a string form.
     * @return - the string form of the instance.
     */
    public String toString() {
        return ("(" +  this.left.toString() + " & " + this.right.toString() + ")");
    }

    /**
     * The assign method replaces a variable with an Expression.
     * @param var - the variable that will be replaced.
     * @param expression - the expression that will replace the variable.
     * @return - a new expression generated by the replacement.
     */
    public Expression assign(String var, Expression expression) {
        return new And(left.assign(var, expression), right.assign(var, expression));
    }

    /**
     * The nandify method converts an expression to a nand-only expression equal to the original expression.
     * @return - a nand-only expression equal to the original expression.
     */
    public Expression nandify() {
        return new Nand(new Nand(this.left.nandify(), this.right.nandify()),
                new Nand(this.left.nandify(), this.right.nandify()));
    }

    /**
     * The norify method converts an expression to a nor-only expression equal to the original expression.
     * @return - a nor-only expression equal to the original expression.
     */
    public Expression norify() {
        return new Nor(new Nor(this.left.norify(), this.left.norify()),
                new Nor(this.right.norify(), this.right.norify()));
    }

    /**
     * The simplify method generates a simplified version of an expression instance.
     * @return - a simplified expression instance
     */
    public Expression simplify() {

        if (this.left.toString() == "T" && this.right.toString() != "F") {
            return this.right.simplify();
        }
        if (this.right.toString() == "T" && this.left.toString() != "F") {
            return this.left.simplify();
        }
        if (this.left.toString() == "F" || this.right.toString()  == "F") {
            return new Val(false);
        }
        if (this.left == this.right) {
            return this.left.simplify();
        }
        return new And(this.left.simplify(), this.right.simplify()).simplify();
    }
}

